add caip168 for eip155
ChainAgnostic/namespaces pull request #42
Opened 2022-12-06 02:35 UTC by zachferland

https://github.com/ChainAgnostic/CAIPs/pull/168 - links updated after merge of caip

2022-12-06 08:57 UTC, oed requested changes
A few minor changes needed.

2022-12-06 08:57 UTC, oed commented on eip155/caip168.md
> +### `f(32bytes)` Transaction Type Verification
```suggestion
### `f(bytes32)` Transaction Type Verification
```

Small typo. This should be `bytes32` like the solidity type.

2022-12-06 08:57 UTC, oed commented on eip155/caip168.md
> +3) The first 32 bytes are the function signature and can be discarded, the next 32 bytes is the first argument of the function, which is expected to be a 32 byte hex encoded partial CID.
This should be 4 bytes (8 hex chars).

2022-12-06 08:57 UTC, oed commented on eip155/caip168.md
> +4) The partial CID is a CID with the first two bytes removed, the first byte being the multibase is not needed in byte format, and the second byte being the CID version is not inlcuded, it is assumed
We actually include the entire multihash, but not the CID version nor the ipld codec (which is dag-cbor).

2022-12-06 08:57 UTC, oed commented on eip155/caip168.md
> +This section describes transaction verification when a timestamp anchor proof references a `chainId` in the `eip155` namespace and `txType` is `f(32bytes)`. Type `f(32bytes)` refers to a transaction
Please mention that `f(bytes32)` assumes that a `dag-cbor` CID is being used.

2022-12-06 08:57 UTC, oed commented on eip155/caip168.md
> +discussions-to: <-->
```suggestion
discussions-to: https://github.com/ChainAgnostic/namespaces/pull/42
```

2022-12-15 14:57 UTC, zachferland commented
editorial pass merged

2022-12-21 19:00 UTC, merged