add CAIP-10 for Algorand
ChainAgnostic/namespaces pull request #72
Opened 2023-06-06 06:32 UTC by k13n

Add CAIP-10 definition for Algorand

2023-06-07 13:45 UTC, ehanoc commented
@bumblefudge @ligi Could we get :eyes: on this? Thanks

2023-06-29 13:41 UTC, bumblefudge commented
Apologies, both ligi and I were on leave the last few weeks.  Just looking at this now, I find the prose sections very clear and explanatory; my only concern is that the `chainId` segment is not optional in CAIP-10, and we do not have a wildcard (i.e. "equally valid on any chainID"), so I would recommend expressing all chainIDs as `mainnet` by default, with other values remaining valid in case you need them later.  My request changes should be enough, if you find them unobjectionable, but also feel free to rework/reword as you see fit and I'll review again.

2023-06-29 13:41 UTC, bumblefudge commented on algorand/caip10.md
> +[A-Z2-7]{57}[AEIMQUY4]
```suggestion
algorand:wGHE2Pwdvd7S12BL5FaOP20EGYesN73k:[A-Z2-7]{57}[AEIMQUY4]
```

2023-06-29 13:45 UTC, bumblefudge commented on algorand/caip10.md
> +Algorand addresses are canonically represented as 58-character long strings, written in all-upper-case. They are independent of the network in which they are used. Addresses are derived from a base32
```suggestion
Algorand addresses are canonically represented as 58-character long strings, written in all-upper-case. Account addresses are independent of the network in which they are used, and should be prefixed by the chainID of mainnet when stored in CAIP-10 format unless another chainID is significant in context (i.e. in a chainID-specific transaction). Addresses are derived from a base32-encoding of a 32-byte key followed by a 4-byte checksum. The base32 padding (`=`) is dropped.
```

2023-06-29 13:46 UTC, bumblefudge requested changes
Looks good, other than suggested caveat!

2023-07-04 15:06 UTC, k13n commented
Thank you, the suggested changes look good to me!

2023-07-04 16:37 UTC, merged